"""Contratos Pydantic compartilhados."""

from fourpro_contracts.auth import (
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginRequest,
    MfaChallengeResponse,
    MfaVerifyRequest,
    RefreshRequest,
    ResetPasswordRequest,
    TokenResponse,
    TokenTypeBearer,
)
from fourpro_contracts.billing import MeContextResponse, PlanSummary, StorageContext
from fourpro_contracts.connectors import (
    ConnectionTestResponse,
    ConnectorCapability,
    ConnectorCatalogResponse,
    DataSourceCreate,
    DataSourceItem,
    DataSourceUpdate,
    PaginatedDataSourceList,
    SyncEnqueueResponse,
    SyncRunItem,
)
from fourpro_contracts.dashboard import (
    DashboardCreate,
    DashboardDetail,
    DashboardExportPackage,
    DashboardSummary,
    DashboardUpdate,
    DashboardWidgetIn,
    DashboardWidgetOut,
    PaginatedDashboardList,
)
from fourpro_contracts.dataset import DatasetItem, PaginatedDatasetList
from fourpro_contracts.desktop_sync import (
    DesktopPublishDashboardRequest,
    DesktopPublishDashboardResponse,
    DesktopPublishDatasetRequest,
    DesktopPublishDatasetResponse,
)
from fourpro_contracts.governance import PromoteDatasetRequest, PromoteDatasetResponse
from fourpro_contracts.ingestion import (
    IngestionItem,
    IngestionLifecycleStatus,
    UploadCreatedResponse,
)
from fourpro_contracts.semantic import (
    PaginatedSemanticModelList,
    QueryRequest,
    QueryResponse,
    SemanticModelCreate,
    SemanticModelItem,
)
from fourpro_contracts.tenant import (
    MemberStorageQuotaPatch,
    TenantAuditLogItem,
    TenantAuditLogListResponse,
    TenantMemberItem,
    TenantMemberListResponse,
    TenantQuotaGroupCreate,
    TenantQuotaGroupItem,
    TenantQuotaGroupListResponse,
    TenantQuotaGroupPatch,
)

__all__ = [
    "MeContextResponse",
    "PlanSummary",
    "StorageContext",
    "DatasetItem",
    "PaginatedDatasetList",
    "IngestionItem",
    "IngestionLifecycleStatus",
    "UploadCreatedResponse",
    "TenantAuditLogItem",
    "TenantAuditLogListResponse",
    "TenantMemberItem",
    "TenantMemberListResponse",
    "TenantQuotaGroupItem",
    "TenantQuotaGroupListResponse",
    "TenantQuotaGroupCreate",
    "TenantQuotaGroupPatch",
    "MemberStorageQuotaPatch",
    "LoginRequest",
    "RefreshRequest",
    "TokenResponse",
    "TokenTypeBearer",
    "MfaChallengeResponse",
    "MfaVerifyRequest",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "ResetPasswordRequest",
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardSummary",
    "DashboardDetail",
    "DashboardWidgetIn",
    "DashboardWidgetOut",
    "PaginatedDashboardList",
    "DashboardExportPackage",
    "PromoteDatasetRequest",
    "PromoteDatasetResponse",
    "ConnectorCapability",
    "ConnectorCatalogResponse",
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceItem",
    "PaginatedDataSourceList",
    "ConnectionTestResponse",
    "SyncEnqueueResponse",
    "SyncRunItem",
    "SemanticModelCreate",
    "SemanticModelItem",
    "PaginatedSemanticModelList",
    "QueryRequest",
    "QueryResponse",
    "DesktopPublishDatasetRequest",
    "DesktopPublishDatasetResponse",
    "DesktopPublishDashboardRequest",
    "DesktopPublishDashboardResponse",
]
